train:
  task: "pretrain"
  out_dir: "./out_1b_ru"
  dataset_dir: "/Volumes/KINGSTON/minilm/ru_1b/data"
  resume_from_checkpoint: false
  resume_checkpoint_kind: "latest"

  eval_interval: 1000
  log_interval: 20
  eval_iters: 100
  always_save_checkpoint: true

  wandb_log: true
  wandb_project: "minilm_1b_ru"
  wandb_run_name: "pretrain_1b_ru_20260525"

  gradient_accumulation_steps: 4
  train_batch_size: 8
  eval_batch_size: 8
  num_workers: 8

  learning_rate: 0.0003
  max_iters: 130000
  weight_decay: 0.1
  beta1: 0.9
  beta2: 0.95
  grad_clip: 1.0

  decay_lr: true
  warmup_iters: 2000

  device: "cuda"
  dtype: "bfloat16"
  compile: true
  backend: "nccl"
  eval_only: false

model:
  dim: 2048
  n_layers: 22
  n_heads: 16
  n_kv_heads: 4
  vocab_size: 32768
  multiple_of: 256
  ffn_dim_multiplier: 1.0
  norm_eps: 0.00001
  max_seq_len: 2048
  dropout: 0.0
  gradient_checkpointing: true
  ce_chunk_size: 2048
  use_liger: true
